name: "build2"
on: # rebuild any PRs and main branch changes
  pull_request:
  label:
    types: [created]
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build-test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  build-test-test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        milliseconds: 1000
